#!/usr/bin/env node

'use strict';

var exec = require('child_process').exec;
function getGitTask(callback) {
  exec('npm link git-task', { cwd: __dirname }, function(err, stdout, stderr) {
    if (err !== null) {
      process.exit(0);
    }
    callback(require('git-task'));
  });
}

function main() {
  getGitTask(function(git_task) {
    git_task.removeTaskFile(function() {
      process.exit(0);
    });
  });
}

main();
