#!/usr/bin/env node

'use strict';

var git_task = require('git-task');

function main() {
  git_task.getCurrentSituation(function (result) {
    if (result > 0) {
      git_task.listRemaining(result);
      process.exit(1);
    } else {
      process.exit(0);
    }
  });
}

main();
